version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in install phase.
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase.
  build:
    commands:
      - mvn -e clean package
  post_build:
    commands:
      - echo Nothing to do in post_build phase.
artifacts:
  files:
    - Procfile
    - target/spring-starter.war
  discard-paths: yes

